services:
  patroy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patroy-service
    restart: unless-stopped
    ports:
      - "4023:4023"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://127.0.0.1:4023/health | grep -q 'healthy' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    security_opt:
      - seccomp=unconfined
    shm_size: "1gb"
